[package]
name = "json-depth-checker"
description = "A library that indicates if a JSON must be flattened"
edition = "2021"

[dependencies]
serde_json = "1.0"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "depth"
harness = false
